"""Centralised Dash component IDs."""

STORE_CONFIG = "store-config"
STORE_RESULTS = "store-results"
STORE_JOB = "store-job"
STORE_SELECTED_GENE = "store-selected-gene"
STORE_HISTORY = "store-history"

TABS_MAIN = "tabs-main"

UPLOAD_COUNTS = "upload-counts"
UPLOAD_LIBRARY = "upload-library"
UPLOAD_METADATA = "upload-metadata"
UPLOAD_STATUS = "upload-status"
BUTTON_RUN_ANALYSIS = "button-run-analysis"
BUTTON_DOWNLOAD_REPORT = "button-download-report"
DOWNLOAD_REPORT = "download-report"
BUTTON_DOWNLOAD_SAMPLE_REPORT = "button-download-sample-report"
DOWNLOAD_SAMPLE_REPORT = "download-sample-report"
INTERVAL_JOB = "interval-job"
INTERVAL_HISTORY = "interval-history"

CONFIG_PANEL = "config-panel"
GRAPH_VOLCANO = "graph-volcano"
GRAPH_QC_REPLICATE = "graph-qc-replicate"
GRAPH_QC_DETECTION = "graph-qc-detection"
GRAPH_PATHWAY_BUBBLE = "graph-pathway-bubble"
TABLE_GENES = "table-genes"
SUMMARY_CARDS = "summary-cards"
GENE_MODAL = "gene-modal"
GENE_MODAL_BODY = "gene-modal-body"
GENE_SPARKLINE = "gene-sparkline"
GENE_BADGES = "gene-badges"
GENE_DOWNLOAD_BUTTON = "gene-download-button"
DOWNLOAD_GENE = "download-gene"

RUN_HISTORY_CONTAINER = "run-history-container"
RUN_HISTORY_EMPTY = "run-history-empty"
RUN_HISTORY_TITLE = "run-history-title"
RUN_HISTORY_ITEM = "run-history-item"

JOB_STATUS_OVERLAY = "job-status-overlay"
JOB_STATUS_TEXT = "job-status-text"
JOB_STATUS_RUNTIME = "job-status-runtime"
JOB_STATUS_WARNINGS = "job-status-warnings"
JOB_STATUS_DISMISS = "job-status-dismiss"
